"""
Migration script for altering the 'name' field of the 'character' model.

Generated by Django 5.1.4 on 2024-12-17 21:52.
"""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class for altering the 'name' field of the 'character' model."""

    dependencies: ClassVar[list] = [
        ("character", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
