"""
Migration script for adding new fields to the character model.

Generated by Django 5.1.4 on 2024-12-18 07:59
"""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class for adding new fields to the character model."""

    dependencies: ClassVar[list] = [
        ("character", "0002_alter_character_name"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="character",
            name="charisma",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="constitution",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="dexterity",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="hitpoints",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="hitpoints_max",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="intelligence",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="mana",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="mana_max",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="strength",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="wisdom",
            field=models.IntegerField(default=10),
        ),
    ]
