"""
Migration script to add experience_points_to_next_level field to character model.

Generated by Django 5.1.4 on 2024-12-18 08:12
"""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add experience_points_to_next_level field to character model."""

    dependencies: ClassVar[list] = [
        ("character", "0003_character_charisma_character_constitution_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="character",
            name="experience_points_to_next_level",
            field=models.IntegerField(default=100),
        ),
    ]
