"""
Migration script for adding Item and InventoryItem models and updating Character model.

Generated by Django 5.1.4 on 2024-12-19 09:47
"""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration creates the Item and InventoryItem models and adds fields to the Character model."""

    dependencies: ClassVar[list] = [
        ("character", "0005_character_active"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("chest", "Chest"),
                            ("legs", "Legs"),
                            ("weapon", "Weapon"),
                            ("shield", "Shield"),
                            ("ring", "Ring"),
                            ("necklace", "Necklace"),
                            ("boots", "Boots"),
                            ("gloves", "Gloves"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("consumable", "Consumable"),
                            ("equipment", "Equipment"),
                            ("quest", "Quest Item"),
                        ],
                        default="equipment",
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("trash", "Trash"),
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("value", models.IntegerField(default=0)),
                ("stacksize", models.PositiveIntegerField(default=1)),
                ("current_durability", models.PositiveIntegerField(default=100)),
                ("max_durability", models.PositiveIntegerField(default=100)),
                ("is_repairable", models.BooleanField(default=False)),
                ("strength_bonus", models.IntegerField(default=0)),
                ("dexterity_bonus", models.IntegerField(default=0)),
                ("intelligence_bonus", models.IntegerField(default=0)),
                ("constitution_bonus", models.IntegerField(default=0)),
                ("wisdom_bonus", models.IntegerField(default=0)),
                ("charisma_bonus", models.IntegerField(default=0)),
                ("hitpoints_bonus", models.IntegerField(default=0)),
                ("mana_bonus", models.IntegerField(default=0)),
                ("required_level", models.PositiveIntegerField(default=1)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="item_icons/"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="max_carry_weight",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="character",
            name="max_inventory_slots",
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("current_durability", models.IntegerField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="character.character",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="character.item",
                    ),
                ),
            ],
        ),
    ]
