name: Ruff Linter Check

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run Ruff Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Working Directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Wähle die passende Python-Version für dein Projekt

      - name: Checking with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."  # Prüft das gesamte Projektverzeichnis

      - name: Display Ruff Version
        run: ruff --version
